### ISSUE TITLE
ERR_FILE_NOT_FOUND (-6) loading 

### ISSUE THREAD

**Issue by iZaiZaiA** [p-sam/electron-prompt#73] opened 2021-04-16 23:01 UTC
```
Uncaught (in promise) Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///xxxx/electron/xxxxxxx/node_modules/_electron@11.4.3@electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/page/prompt.html#1618613897887-0.13384548012489894'
    at rejectAndCleanup (electron/js2c/browser_init.js:205)
    at Object.failListener (electron/js2c/browser_init.js:205)
    at Object.emit (events.js:315)

```

<hr/>

```
"vue-cli-plugin-electron-builder": "^2.0.0-rc.6",
"electron": "^11.0.0",
"vue": "^2.6.11",
"electron-prompt": "^1.6.2",
```

**Comment by p-sam** [comment] 2021-04-17 11:47
Hi, first things first, please submit a short code that can reproduce the error you sent along with a description. Also this looks like a duplicate of #64 

I'll close this and reopen if new information is brought

**Closed as completed by p-sam** 2021-04-17 11:47 UTC
