### ISSUE TITLE
testing example prompt: label and input field not displayed, cancel and ok buttons unstyled

### ISSUE THREAD

**Issue by stepheneb** [p-sam/electron-prompt#79] opened 2021-10-26 00:44 UTC
Using electron-prompt 1..7.0

Also:
```
node --version: 
v14.18.1
electron --version: 
v13.2.3
electron-forge: 
...
└─┬ @electron-forge/plugin-webpack@6.0.0-beta.61
  └── webpack@5.52.1 
```

Am calling prompt() in response to a menu action:

'''
      {
        label: "CfA Key",
        enabled: true,
        click() {
          cfa.prompt();
        }
      }
'''

Which calls this function in the main process:

```
let cfa_prompt = () => {
  prompt({
      title: 'Prompt example',
      label: 'URL:',
      value: 'http://example.org',
      inputAttrs: {
        type: 'url'
      },
      type: 'input'
    })
    .then((r) => {
      if (r === null) {
        console.log('user cancelled');
      } else {
        console.log('result', r);
      }
    })
    .catch(console.error);
};
```

Which displays:

![image](https://user-images.githubusercontent.com/7188/138789209-4d977f3f-9353-480d-ac43-c67a902cf004.png)

Seems related to #55 -- which is closed ... but I I didn't see a resolution in the comments for that issue???

**Comment by lucasreppewelander** [comment] 2021-12-16 22:58
i have the same, with webpack the prompt.html gets placed inside the `.webpack/main/native_modueles` but only the html file, not the css nor js file, thats the main issue.

**Comment by p-sam** [comment] 2021-12-17 00:33
Yup, as it was in #55 if you end up treating electron-prompt like a frontend dependancy, it won't work, you gotta explicitely use the node require. Since this seems like a duplicate of a non-issue, there's not much point in leaving this open further

**Closed as completed by p-sam** 2021-12-17 00:33 UTC
