### ISSUE TITLE
Validate form on Enter/return key pressed

### ISSUE THREAD

**Issue by fperaltaa** [p-sam/electron-prompt#62] opened 2020-07-23 12:22 UTC
If you add the **pattern** attribute to the input, it is nos being validated when you submit the form pressing "Enter" key.

**Comment by p-sam** [comment] 2020-07-23 12:45
Seems like a duplicate of #52, can you try on the develop branch and confirm?

**Comment by fperaltaa** [comment] 2020-07-23 13:35
@p-sam I'm using version 1.5.1 where the input is already inside a form. The pattern is being validated on submit with the "ok" button but not when I hit "Enter".
It is related with #52, we can close this and reopen that one if you wish.

**Comment by p-sam** [comment] 2020-07-23 13:48
I see, thanks for the clarification

**Closed as completed** 2020-07-25 15:38 UTC

**Comment by p-sam** [comment] 2020-07-25 15:50
Please confirm the issue is resolved on your end too in the develop branch, then I'll wrap up a new release

**Comment by fperaltaa** [comment] 2020-07-27 12:33
Thanks @p-sam ! I tried with develop branch and it is working as expected.
