### ISSUE TITLE
No content but buttons, buttons aren't working, seems like index.html isn't being loaded

### ISSUE THREAD

**Issue by stepheneb** [p-sam/electron-prompt#55] opened 2020-02-13 02:06 UTC
Am trying to use electron-prompt to make a dialog with a numeric input.

Am getting this result.

![image](https://user-images.githubusercontent.com/7188/74393268-9b7a1c80-4dd7-11ea-836d-1ed9520ec689.png)

After clicking either the button the only change appears to be that the background changes to white:

![image](https://user-images.githubusercontent.com/7188/74393329-c6fd0700-4dd7-11ea-9f08-5a843ee3310c.png)
Environment:

```
node --version: 
v12.14.1
electron --version: 
v8.0.0
electron-forge --version: 
✔ Checking your system
6.0.0-beta.49

```
Code;

```javascript
const promptOptions = {
  title: 'Run Bubble Sort example',
  label: 'ms delay:',
  // buttons: ['Cancel', 'Yes'],
  value: 10,
  inputAttrs: {
    type: 'number',
    // min: "1",
    // max: "1000"
  },
  type: 'input'
};

examples.promptRun = () => {
  const bw = BrowserWindow.getFocusedWindow();
  prompt(promptOptions, bw)
    .then((response) => {
      if (response === null) {
        // Cancel: button 0 clicked
      } else {
        examples.bubblesort();
      }
    })
    .catch(console.error);
};
```
I also noticed a strange problem where webpack gave an error when I tried to debug into the prompt code.

Attempting to step into:

![image](https://user-images.githubusercontent.com/7188/74394382-85219000-4dda-11ea-937b-41c7bfdf6c25.png)

I get this error:

```
Could not load content for webpack:///./node_modules/electron-prompt/lib/index.js : HTTP status code: 404
```
The only difference I noticed with other npm modules I could debug into is that `index.js` is in the lib dir. Others I could debug into `index.js` was one level higher.

![image](https://user-images.githubusercontent.com/7188/74394538-ca45c200-4dda-11ea-9014-11389821f3ce.png)

I cloned electron-forge locally and moved index.js up one level (and the code in the page folder up one leve also) and change the code so `index.js` loads dependent resources form the lib directory.

With these changes I coulod step into prompt -- but all I got then was just a white window. 

Thought I'd report the issues before I looked further.

**Comment by p-sam** [comment] 2020-02-13 07:15
Duplicate of #34

**Closed as completed by p-sam** 2020-02-13 07:15 UTC
