### ISSUE TITLE
Error: Image could not be created from \n

### ISSUE THREAD

**Issue by nullxx** [p-sam/electron-prompt#59] opened 2020-05-10 09:42 UTC
In the  "electron": "^9.0.0-beta.15" a error occurs: 
```
{
  constructor: 'Error',
  stack: 'Error: Image could not be created from \n' +
    '    at electron/js2c/browser_init.js:6983:49\n' +
    '    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:6880:27)\n' +
    '    at IpcMainImpl.emit (events.js:223:5)\n' +
    '    at WebContents.<anonymous> (electron/js2c/browser_init.js:4070:23)\n' +
    '    at WebContents.emit (events.js:223:5)'
}
```

It works well if: 
```
let promptWindow = new BrowserWindow({
			width: opts.width,
			height: opts.height,
			minWidth: opts.minWidth,
			minHeight: opts.minHeight,
			resizable: opts.resizable,
			parent: parentWindow,
			skipTaskbar: true,
			alwaysOnTop: opts.alwaysOnTop,
			useContentSize: opts.resizable,
			modal: Boolean(parentWindow),
			title: opts.title,
			// icon: opts.icon, <- comment this line
			webPreferences: {
				nodeIntegration: true
			}
		});
```

**Comment by wgrhstf** [comment] 2020-05-26 08:40
I have the same error on 9.0.0 stable

If you change line 29 in `const opts` in index.js from 
`icon: null,` to `icon: false,`
it works as expected.

**Comment by p-sam** [comment] 2020-05-26 14:49
duplicate of #57

This already has been fixed in develop, but not published to npm yet

**Closed as completed by p-sam** 2020-05-26 14:49 UTC
